#:kivy 2.0.0
#:import RetryImage widgets.image.RetryImage
#:import RippleButton widgets.button.RippleButton

<CategoriesScreen>:
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            size_hint_y: None
            height: dp(48)
            RippleButton:
                text: '用户'
                size_hint_x: 1
                font_size: dp(28)
                color: rgba('#ffffffff')
            Label:
                text: ''
                size_hint_x: 3
            RippleButton:
                size_hint_x: 1
                text: '搜索'
                font_size: dp(28)
                color: rgba('#ffffffff')
                on_release: root.open_search()
        ScrollView:
            id: scroll
            do_scroll_x: False
            GridLayout:
                id: gl
                cols: 3
                size_hint_y: None
                spacing: dp(8), dp(8)
                padding: dp(8), dp(8)
                height: self.minimum_height
                CategoryItem:
                    image_path: 'img/leaderboard.jpg'
                    text: '哔咔排行榜'
                    is_web: True
                    img_saved: True
                    on_release: root.manager.screen_open('leaderboard')

<CategoryItem>:
    orientation: 'vertical'
    height: self.minimum_height
    size_hint_y: None
    RetryImage:
        size_hint: 1, None
        id: image
        path: root.image_path
        saved: root.img_saved
        height: self.width
    Label:
        size_hint_y: None
        text: root.text
        height: dp(20)
