#:kivy 2.0.0
#:import Header widgets.header.Header
#:import RippleButton widgets.button.RippleButton

<CommentsScreen>:
    BoxLayout:
        orientation: 'vertical'
        Header:
            title: '评论区'
        BoxLayout:
            size_hint_y: None
            height: dp(30)
            RippleButton:
                text: '上一页'
                on_release: root.prev_page()
            RippleButton:
                text: '下一页'
                on_release: root.next_page()
        ScrollView:
            do_scroll_x: False
            BoxLayout:
                id: docs
                size_hint_y: None
                height: self.minimum_height
                orientation: 'vertical'
