#:kivy 2.0.0
#:import Header widgets.header.Header
#:import RippleButton widgets.button.RippleButton

<LeaderBoardScreen>:
    BoxLayout:
        orientation: 'vertical'
        Header:
            title: '哔咔排行榜：' + root.txts[root.rid]
        BoxLayout:
            size_hint_y: None
            height: self.minimum_height
            RippleButton:
                size_hint: 1, None
                height: dp(30)
                text: root.txts[0]
                on_release: root.rid = 0
            RippleButton:
                size_hint: 1, None
                height: dp(30)
                text: root.txts[1]
                on_release: root.rid = 1
            RippleButton:
                size_hint: 1, None
                height: dp(30)
                text: root.txts[2]
                on_release: root.rid = 2
        ScrollView:
            do_scroll_x: False
            BoxLayout:
                id: docs
                height: self.minimum_height
                size_hint_y: None
                orientation: 'vertical'
